# Birds CUB dataset
birds_images_path: '/export/mlrg/aelnouby/projects/GANs/Birds dataset/CUB_200_2011/CUB_200_2011/images/'
birds_embedding_path: '/export/mlrg/aelnouby/projects/GANs/Birds dataset/cub_icml/'
birds_text_path: '/export/mlrg/aelnouby/projects/GANs/Birds dataset/cvpr2016_cub/text_c10/'
birds_dataset_path: '/scratch/aelnouby/text2image/birds.hdf5'
val_split_path: '/export/mlrg/aelnouby/projects/GANs/Birds dataset/cub_icml/valclasses.txt'
train_split_path: '/export/mlrg/aelnouby/projects/GANs/Birds dataset/cub_icml/trainclasses.txt'
test_split_path: '/export/mlrg/aelnouby/projects/GANs/Birds dataset/cub_icml/testclasses.txt'


# flowers dataset
flowers_images_path: '/zf18/fz2ds/Text2Image/Text2ImageGenerateModel/flowers/images/'
flowers_embedding_path: '/zf18/fz2ds/Text2Image/Text2ImageGenerateModel/flowers/w2v_c10/'
flowers_text_path: '/zf18/fz2ds/Text2Image/Text2ImageGenerateModel/flowers/text_c10/'
flowers_dataset_path: '/zf18/fz2ds/Text2Image/Text2ImageGenerateModel/flowers.hdf5'

flowers_val_split_path: '/zf18/fz2ds/Text2Image/Text2ImageGenerateModel/flowers/valclasses.txt'
flowers_train_split_path: '/zf18/fz2ds/Text2Image/Text2ImageGenerateModel/flowers/trainclasses.txt'
flowers_test_split_path: '/zf18/fz2ds/Text2Image/Text2ImageGenerateModel/flowers/testclasses.txt'
